Basic documents and DB CRUD commands
ravendb/ravendb-cpp-client pull request #1
Opened 2018-11-12 12:07 UTC by sashatim125

2018-11-14 09:18 UTC, ayende requested changes

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +	const std::string RAVEN_SERVER_URL = "http://localhost:8080";
Let's define all of these values in a single file / location.
That includes constants like the server url but also the entities / serialization code.
It shouldn't be in the same file as the tests

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		return (str.compare(0, test_prefix.length(), test_prefix) == 0);
what is this is too small to be a prefix?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		serverwide::operations::GetDatabaseNamesCommand cmd(0, 100);
Why are you deleting all the databases?
You should only delete the databases _for that particular test_

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		serverwide::operations::GetDatabaseNamesCommand cmd(0, 100);
in `SetupTestCase`, add new db name to a vector ` clear it in the `TeadDownTestCase`

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		serverwide::operations::GetDatabaseNamesCommand cmd(0, 100);
The reason for this is that we want to be able to run these tests concurrently at one point, and that would prevent that.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +const std::string DocumentCommandsTests::db{ "TEST__DocumentCommandsTests" };
We don't need any special prefix

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +const std::string DocumentCommandsTests::db{ "TEST__DocumentCommandsTests" };
we can use  "__func__ -__LINE" to generate unique db name more easily, no?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +	auto executor = http::RequestExecutor::create({ RAVEN_SERVER_URL }, db_name);
Any reason you keep creating new request executors? The common use case (and certainly the one we want to test) it to hold to one and use it multiple times.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		if (doc.at("@metadata").at("@id").get<std::string>() == doc_id)
This will fail for case insensitivity

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		if (std::string(doc.type_name()) == "null")
doc is a json token here?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +	{
why the scope here?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +	for (auto& doc : res.results)
This should be replaced with a call to `does_document_exist`

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +	const std::string RAVEN_SERVER_URL = "http://localhost:8080";
Same as before, we want to have _one_ such definition for the tests.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +	static const std::string cdd_db;
what is the meaning of `cdd` and `cgdr`?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +	static bool contains_test_prefix(const std::string& str)
same as previous, and probably not required

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +		for(const auto& dbname : res)
See previous test, you shouldn't be writing this but know, upfront, what dbs you delete

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +const std::string RequestExecutorTests::cgdr_db{ "TEST__CanGetDatabaseRecord" };
Use `CreateDatabase(__func__)` instead to generate dbs

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +{//TODO refactor this for using exceptions and unsync
unsync?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +		auto ex = dynamic_cast<RavenError*>(&exception);
Can't you just catch `RavenError` directly?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +
Trim the file please

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/ConflictSolver.h
> +		bool resolve_to_latest = true;//am I right ?
`resolve_to_latest` is the default, yes.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/CreateDatabaseCommand.h
> +		std::unique_ptr<DatabaseRecord> _database_record;//polymorphism is needed
why?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/CurlHandlesHolder.h
> +				if (res not_eq CURLE_OK)
why `not_eq` ?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/CurlHandlesHolder.h
> +				: _curl(std::move(other._curl))
remove commented code

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/DatabasePutResult.h
> +		//dpr.topology = j.at("Topology").get<DatabaseTopology>();
why is this commented?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/DatabaseTopology.h
> +		std::vector<std::string> members{};
can't we define this just as `;` without `{};`?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/DeleteDatabaseCommand.h
> +	using TimeToWaitForConfirmation_t = std::chrono::milliseconds; //which units should we use ?
We use milliseconds
But I don't like the `TimeToWait..` it actually obscures what is going on. Use `std::chrono::milliseconds` directly

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/DeleteDatabaseCommand.h
> +		DeleteDatabaseParameters _parameters{};
why parameters and not have this directly on this class?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/DeleteDocumentCommand.h
> +				_headers_list = curl_slist_append(_headers_list, change_vector_header.str().c_str());
who owns the memory in `_headers_list` ?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +		struct DatabaseNames_t//used with to/from json
We need to make a consistent decision on class names.
`DatabaseNames_t` is ugly in my eyes.
I think that class names should be `snake_case` to match the common behavior from the library.

@maximburyak thoughts?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +			if (it == j.end() or not it->is_array())
`or not` ? 
Please don't use the alternative operators.

Also, isn't an empty array valid response here?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +			if (statusCode == 200)
What about error handling when the result is not 200?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDatabaseRecordCommand.h
> +			if (statusCode == 200)
What about error handling when the result is not 200?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDatabaseTopologyCommand.h
> +			else
What about error handling when the result is not 200 / 404? What happens if you don't have authorization, for example.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDocumentsCommand.h
> +			{
Note you need to handle this as well

https://github.com/ravendb/ravendb/commit/f0366efc7361b7c45cc0b3fcffe4b1d932f64f41

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/GetDocumentsCommand.h
> +			if (statusCode == 200)
error handling

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/RavenTest.cpp
> +TEST(TestCaseName, TestName) {
can remove this

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/RequestExecutor.cpp
> +		if (not rq->_db_name.empty())
This is actually a lot more readable than `!`, maybe just allow `not`, @maximburyak?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/RequestExecutor.h
> +					cmd.set_response(curl, result, false);
Note that `set_response` is called _only_ for 200 / 2001, never for anything else.
That means that any code in `set_response` that try to handle that shouldn't.

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/RequestExecutor.h
> +			std::shared_ptr<Topology> topology_local = std::atomic_load(&_topology);
Is this safe? Is this going to safely inc the ref count in multi threaded fashion?

2018-11-14 09:18 UTC, ayende commented on Raven.CppClient/RequestExecutor.h
> +					errors << re.what() << '\n';
Errors are rare, what is the cost of creating the `errors` on each call?

2018-11-14 14:10 UTC, sashatim125 commented on Raven.CppClient/RequestExecutor.h
> +					errors << re.what() << '\n';
according to [this](https://en.cppreference.com/w/cpp/io/basic_stringbuf) not much,
but using std::optional seems like reasonable optimization

2018-11-14 14:32 UTC, sashatim125 commented on Raven.CppClient/RequestExecutor.h
> +			std::shared_ptr<Topology> topology_local = std::atomic_load(&_topology);
Yes.
according to [this](https://en.cppreference.com/w/cpp/memory/shared_ptr/atomic) :

> If multiple threads of execution access the **same** std::shared_ptr **object** without synchronization and any of those accesses uses a non-const member function of shared_ptr then a data race will occur unless all such access is performed through these functions, which are overloads of the corresponding atomic access functions (std::atomic_load, std::atomic_store, etc.)
> 
> Note that the control block of a shared_ptr is thread-safe: **different** std::shared_ptr **objects** can be accessed using mutable operations, such as operator= or reset, simultaneously by multiple threads, even when these instances are copies, and share the same control block internally.

2018-11-14 15:00 UTC, sashatim125 commented on Raven.CppClient/DeleteDocumentCommand.h
> +				_headers_list = curl_slist_append(_headers_list, change_vector_header.str().c_str());
curl_slist* is a pointer to linked list's head, while the list is allocated on the heap
so  curl_slist_append returns a new head (or NULL)
(so my code wasn't safe line 51).
curl_easy_setopt(curl, CURLOPT_HTTPHEADER, _headers_list) makes
the curl_easy_perform() use this list, i.e. it's used beyond the function where it
was created , so RAII is unappropriate

2018-11-14 15:21 UTC, sashatim125 commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +			if (it == j.end() or not it->is_array())
> Also, isn't an empty array valid response here?

it sure is ,like this 

> {
"Databases": [ ]
}

but absence of the "Databases" key in return json
or if it's value isn't an array is an error

2018-11-14 15:49 UTC, sashatim125 commented on Raven.CppClient/RequestExecutor.h
> +					errors << re.what() << '\n';
we can also keep the list of all exceptions(std::exception_ptr)
(probably as std::optional too)
and creates the errors string only when throwing

2018-11-14 15:53 UTC, sashatim125 commented on Raven.CppClient/RequestExecutor.h
> +					cmd.set_response(curl, result, false);
OK, unnecessary code removed

2018-11-14 18:25 UTC, ayende commented on Raven.CppClient/RequestExecutor.h
> +					errors << re.what() << '\n';
If the cost is cheap, let's just leave it.

2018-11-14 18:26 UTC, ayende commented on Raven.CppClient/DeleteDocumentCommand.h
> +				_headers_list = curl_slist_append(_headers_list, change_vector_header.str().c_str());
So the issue is value you appened (the `change_vector_header`) is copied or referenced?

2018-11-15 07:21 UTC, sashatim125 commented on Raven.CppClient/DeleteDocumentCommand.h
> +				_headers_list = curl_slist_append(_headers_list, change_vector_header.str().c_str());
copied , as mentioned [here](https://curl.haxx.se/libcurl/c/curl_slist_append.html) :

> curl_slist_append appends a string to a linked list of strings. The existing list should be passed as the first argument and the new list is returned from this function. Pass in NULL in the list argument to create a new list. The specified string has been appended when this function returns. curl_slist_append **copies** the string.
> 
> The list should be freed again (after usage) with curl_slist_free_all.

2018-11-15 07:27 UTC, sashatim125 commented on Raven.CppClient/RavenTest.cpp
> +TEST(TestCaseName, TestName) {
done

2018-11-15 07:36 UTC, sashatim125 commented on Raven.CppClient/DeleteDatabaseCommand.h
> +	using TimeToWaitForConfirmation_t = std::chrono::milliseconds; //which units should we use ?
done

2018-11-15 08:02 UTC, sashatim125 commented on Raven.CppClient/DeleteDatabaseCommand.h
> +		DeleteDatabaseParameters _parameters{};
it's the java code design, 
where this command is actually wrapped by DeleteDatabasesOperation,
so the Parameters object is a block that is passed by the operation 
to the command upon it's creation (by getCommand() )
so in my code this ctor
```
DeleteDatabaseCommand(std::string database_name, bool hard_delete, std::string from_node = {},
			std::chrono::milliseconds time_to_wait_for_confirmation = default_wait_time)
```
will be move to operation and only this one
`DeleteDatabaseCommand(DeleteDatabaseParameters parameters)`
will be left.

2018-11-15 08:15 UTC, sashatim125 commented on Raven.CppClient/DatabaseTopology.h
> +		std::vector<std::string> members{};
surely we can !
but it's a safety habit , a part of the wider one "do not leave members uninitialized".
also explicitly calling default ctor when it doesn't exist 
results in compilation error , that way reminding to make
the initialization in the non_default ctor.

2018-11-17 21:12 UTC, maximburyak commented on Raven.CppClient/RequestExecutor.cpp
> +		if (not rq->_db_name.empty())
I prefere not using alternative logical operators at all. Bear in mind this should be easy to read to other team members as well

2018-11-17 21:18 UTC, maximburyak commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +		struct DatabaseNames_t//used with to/from json
We discussed it with @sashatim125 and it seems best to go the camelcase route. This way code will be easier to port, readable to non cpp guys and more explorable and comparable to other clients, which all written using variations of camelCase

2018-11-18 06:43 UTC, ayende commented on Raven.CppClient/GetDatabaseNamesCommand.h
> +		struct DatabaseNames_t//used with to/from json
camelCase route isn't common in C++
I would rather go with the std lib naming conventions

2018-11-18 14:37 UTC, sashatim125 commented on Raven.CppClient/GetDocumentsCommand.h
> +			{
done 
(unused now, though, because we don't have the http cash yet)

2018-11-18 14:47 UTC, sashatim125 commented on Raven.CppClient/RequestExecutor.h
> +					cmd.set_response(curl, result, false);
http response code for now is processed in RequestExecutor only

2018-11-18 15:06 UTC, sashatim125 commented on Raven.CppClient/DatabasePutResult.h
> +		//dpr.topology = j.at("Topology").get<DatabaseTopology>();
because the DatabaseTopology deserialization (from_json) routine was not yes written.
it is now, but should be tested because of it's complexity

2018-11-18 15:16 UTC, sashatim125 commented on Raven.CppClient/CurlHandlesHolder.h
> +				: _curl(std::move(other._curl))
done

2018-11-18 15:18 UTC, sashatim125 commented on Raven.CppClient/CurlHandlesHolder.h
> +				if (res not_eq CURLE_OK)
checking if the initialization succeeded 
(now replaced with != )

2018-11-18 15:49 UTC, sashatim125 commented on Raven.CppClient/CreateDatabaseCommand.h
> +		std::unique_ptr<DatabaseRecord> _database_record;//polymorphism is needed
because (along with original c# code)  the base class DatabaseRecord is derived with DatabaseRecordWithEtag
(adding etag only)
```
    public class DatabaseRecordWithEtag : DatabaseRecord
    {
        public long Etag { get; set; }
    }
```
I think it's an overkill, and I propose to use DatabaseRecord only with (perhaps std::optional)
etag. What do you think ?

2018-11-18 15:56 UTC, sashatim125 commented on Raven.CppClient/ConflictSolver.h
> +		bool resolve_to_latest = true;//am I right ?
OK

2018-11-18 15:57 UTC, sashatim125 commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +
done

2018-11-19 08:00 UTC, ayende commented on Raven.CppClient/CreateDatabaseCommand.h
> +		std::unique_ptr<DatabaseRecord> _database_record;//polymorphism is needed
Yes, go ahead

2018-11-21 15:23 UTC, sashatim125 commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +		auto ex = dynamic_cast<RavenError*>(&exception);
yes. done like your said

2018-11-21 15:24 UTC, sashatim125 commented on Raven.CppClient.Tests/RequestExecutorAndDBsTests.cpp
> +{//TODO refactor this for using exceptions and unsync
typo , means async 
anyway,corrected now

2018-11-21 15:29 UTC, sashatim125 commented on Raven.CppClient.Tests/DocumentCommandsTests.cpp
> +		if (doc.at("@metadata").at("@id").get<std::string>() == doc_id)
yes.
it seems like that comparison  was  unnecessary , since if the document exists,
it is returned, otherwise null is returned .
the order of documents (or nulls) is matched to the order of ids in the request

2018-11-21 20:35 UTC, merged